"""added supplier field in Purchase

Revision ID: 6ca9b199c6b7
Revises: ed5146be8a31
Create Date: 2026-03-24 13:14:04.406196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ca9b199c6b7'
down_revision: Union[str, Sequence[str], None] = 'ed5146be8a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'supplier')
    # ### end Alembic commands ###
