"""field selling_price was added to PurchaseItem

Revision ID: ed5146be8a31
Revises: 32eb2b23b95a
Create Date: 2026-03-22 22:12:56.368132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed5146be8a31'
down_revision: Union[str, Sequence[str], None] = '32eb2b23b95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseitem', sa.Column('selling_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchaseitem', 'selling_price')
    # ### end Alembic commands ###
